version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=qna_project.settings

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: qna_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 071102
      MYSQL_ROOT_PASSWORD: 071102
    ports:
      - "3306:3306"
